sudo: true
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
install:
  - sudo apt update
  - sudo apt install devscripts build-essential debhelper -y
  - sudo apt install dh-autoreconf qtbase5-dev qtbase5-private-dev fonts-noto-cjk librime-dev libxkbcommon-dev wayland-protocols libglib2.0-dev pkg-config intltool libgtk-3-dev libgtk-3-bin libgtk2.0-dev libqt4-dev libappindicator3-dev librsvg2-bin libhangul-dev libanthy-dev anthy libchewing3-dev libxkbcommon-dev libwayland-dev libaudit-dev -y
  
script:
  - dpkg-checkbuilddeps
  - debuild -S
