sudo: true
matrix:
  include:
    - os: linux
      dist: xinial
      sudo: required
    - os: linux
      dist: bionic
      sudo: required
install:
  - sudo apt update
  - sudo apt install devscripts build-essential debhelper -y
  - sudo apt install libglib2.0-dev pkg-config intltool libgtk-3-dev libgtk-3-bin libgtk2.0-dev libqt4-dev qtbase5-dev qtbase5-private-dev libappindicator3-dev librsvg2-bin fonts-noto-cjk libhangul-dev libanthy-dev anthy libchewing3-dev librime-dev libxkbcommon-dev libwayland-dev wayland-protocols libaudit-dev -y
  
script:
  - dpkg-checkbuilddeps
  - debuild -S
